### ISSUE TITLE
Incorporate Pan-African-Latin shaperglot profiles directly into shaperglot

### ISSUE THREAD

**Issue by NeilSureshPatel** [simoncozens/shaperglot#10]
@simon, per our discussion today, here is a [link](https://github.com/NeilSureshPatel/font-lang-support-afr/tree/main) to `sg-bulk-builder.py` which I am using to create shaperglot profiles. Currently, it only builds the no_orphaned_marks test. There is some setup for the forthcoming unencoded glyph variant test. I also was planning a smcp test for orthographies, but that seems like an easy thing to roll into default orthographies test with a conditional feature switch for smcp.

**Comment by simoncozens** [comment]
I've added this to the repo, and changed its directory so that it writes to shaperglot/languages directly. I've also committed its output to the repo.

**Comment by NeilSureshPatel** [comment]
Thanks, Simon. Everything seems to working well!
