### ISSUE TITLE
Installing Shaperglot

### ISSUE THREAD

**Issue by NeilSureshPatel** [simoncozens/shaperglot#4]
I know the overview says "Development has barely started, so don't try using this yet." but tried to install Shaperglot anyway :)
Got the following error. 

`ERROR: Could not find a version that satisfies the requirement shaperglot (from versions: none)'

'ERROR: No matching distribution found for shaperglot`

We just kicked off the African language support work with Google, so I am curious if there is a dev version I could start working with. 

Thanks.

**Comment by kontur** [comment]
Shaperglot is not on pip as of yet, it seems. With latest pip versions you should be able to use:

```
pip install git+ssh://git@github.com/simoncozens/shaperglot.git
```

**Comment by NeilSureshPatel** [comment]
Perfect! Thanks that did the trick.
